config/routes.rb
RailwaysAndStations::Application.routes.draw do
  resources :railways

  root "welcome#index"

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :railway
  has_many :points, dependent: :destroy
  accepts_nested_attributes_for :points, :allow_destroy => true
  
  validates_presence_of :description
  validates_presence_of :color
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :branch
end

app/models/railway.rb
class Railway < ActiveRecord::Base
  has_many :branches, dependent: :destroy
  accepts_nested_attributes_for :branches, :allow_destroy => true
  
  validates_presence_of :name
  validates_presence_of :abbreviation
  validates_presence_of :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  #Set locale with URL parameter
  #before_action :set_locale
 
  #def set_locale
  #  I18n.locale = params[:locale] || I18n.default_locale
  #end
end

app/controllers/railways_controller.rb
class RailwaysController < ApplicationController
  before_action :set_railway, only: [:show, :edit, :update, :destroy]

  # GET /railways
  # GET /railways.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: RailwaysDatatable.new(view_context) }
    end
  end

  # GET /railways/1
  # GET /railways/1.json
  def show
  end

  # GET /railways/new
  def new
    @railway = Railway.new
  end

  # GET /railways/1/edit
  def edit
  end

  # POST /railways
  # POST /railways.json
  def create
    @railway = Railway.new(railway_params_with_ids)

    respond_to do |format|
      if @railway.save
        format.html { redirect_to @railway, notice: 'Railway was successfully created.' }
        format.json { render action: 'show', status: :created, location: @railway }
      else
        format.html { render action: 'new' }
        format.json { render json: @railway.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railways/1
  # PATCH/PUT /railways/1.json
  def update
    respond_to do |format|
      if @railway.update(railway_params_with_ids)
        format.html { redirect_to @railway, notice: 'Railway was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @railway.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railways/1
  # DELETE /railways/1.json
  def destroy
    @railway.destroy
    respond_to do |format|
      format.html { redirect_to railways_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railway
      @railway = Railway.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def railway_params
      params.require(:railway).permit(:name, :abbreviation, :description, 
      :branches_attributes => [:description, :color,
        :points_attributes => [:latitude, :longitude]])
    end
    
    # Pemit id also to delete and update
    def railway_params_with_ids
      params.require(:railway).permit(:name, :abbreviation, :description, 
      :branches_attributes => [:id, :description, :color, :_destroy,
        :points_attributes => [:id, :latitude, :longitude, :_destroy]])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_row(name, f, association, table_id, html_options={})
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.simple_fields_for(association, new_object, :child_index => "new_#{association}", :branchIdx => f.options[:child_index]) do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    
    html_options['data-addRow-association'] = association
    html_options['data-addRow-tableid'] = table_id
    html_options['data-addRow-content'] = fields.to_str
    link_to name, '#', html_options
  end
  
  def link_to_destroy_row(name, f, html_options={})
    html_options['data-removeRow'] = true
    f.hidden_field(:_destroy) + link_to(name, "#", html_options)
  end
end

app/helpers/railways_helper.rb
module RailwaysHelper
  def link_to_edit_branch_track(name, f, association, html_options={})
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.simple_fields_for(association, new_object, :child_index => "new_#{association}", :branchIdx => f.options[:child_index]) do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    
    html_options['data-editBranchTrack-association'] = association
    html_options['data-editBranchTrack-pointContent'] = fields.to_str
    
    link_to name, '#', html_options
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
	<hr>
	
	<footer>
		<p>© Company 2013</p>
	</footer>
</div>

app/views/layouts/_menu.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
  	<div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to t(:app_name), "/", :class => "brand" %>
      
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to t('activerecord.models.railway.other'), railways_path %></li>
          <li></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
        
        <p class="navbar-text pull-right">
          Logged in as <a href="#" class="navbar-link">Username</a>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%
  flash.each do |key, value|
    if (key.eql? :notice)
%>
    <div class="alert alert-success fade in" data-alert="alert">
    	<a class="close" data-dismiss='alert' href="#">×</a>
    	<p><%= value %></p>
  	</div>
<%
    else
%>
    <div class="alert alert-danger fade in" data-alert="alert">
    	<a class="close" data-dismiss='alert' href="#">×</a>
    	<p><%= value %></p>
  	</div>
<%
    end
  end
%>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8">
    <title><%=t :app_name %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- Le styles -->
    <%= csrf_meta_tags %>
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    
    <%= stylesheet_link_tag "application" %>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->
  </head>

	<body>
		<%= render "layouts/menu"%>
		<%= render "layouts/messages"%> 
		<%= yield %>
		<%= render "layouts/footer"%>
		<%= javascript_include_tag "application" %>
		<%= yield :finalize %>
	</body>
</html>

app/views/railways/_branch_fields.html.erb
<tr>
	<td>
		<%= f.hidden_field :id, 'data-branchIdx' => f.options[:child_index] %>
		<%= f.simple_fields_for :points, :branchIdx => f.options[:child_index] do |builder| %>
			<%= render "point_fields", :f => builder %>
		<% end %>
		<%= f.input :description, :label => false, 'data-branchIdx' => f.options[:child_index]  %>
	</td>
	<td>
		<%= f.input_field :color, :value => (f.object.color.blank? ? 'FF0000' : f.object.color), :class => 'input-mini pick-a-color', 'data-branchIdx' => f.options[:child_index]  %>
	</td>
	<td>
	<%= link_to_edit_branch_track t('custom.models.branch.edit_track'), f, :points, :class => "btn btn-mini btn-primary", 'data-branchIdx' => f.options[:child_index] %>
	<%= link_to_destroy_row t('helpers.submit.delete', model: t('activerecord.models.branch.one')), f, :class => "btn btn-mini btn-danger", 'data-branchIdx' => f.options[:child_index] %>
	</td>
</tr>

app/views/railways/_form.html.erb
<%= simple_form_for(@railway, defaults: { input_html: { class: 'form-horizontal' } }) do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :abbreviation %>
    <%= f.input :description %>
  </div>

  <hr>
  
  <div class="row">
  	<div class="span1">
      <h3><%= t 'activerecord.models.branch.other' %></h3>
    </div>
    <div class="span2">
      <%= link_to_add_row t('helpers.submit.create', model: t('activerecord.models.branch.one')), f, :branches, :branches_table %>
    </div>
  </div>
  
  <table id="branches_table" class="table table-condensed table-hover table-striped table-bordered table-borderless">
  	<thead>
	  	<tr>
	      <th><%= t 'activerecord.attributes.branch.description' %></th>
	      <th><%= t 'activerecord.attributes.branch.color' %></th>
	      <th></th>
	    </tr>
  	</thead>
    <tbody>
    <%= f.simple_fields_for :branches do |builder| %>
  	    <%= render "branch_fields", :f => builder %>
    <% end %>
    </tbody>
  </table>

  <div class="Flexible-container" id="map_canvas"></div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<% content_for :finalize do %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false" %>
  <%= javascript_include_tag "railways" %>
<% end %>

app/views/railways/_point_fields.html.erb
<%= f.hidden_field '_destroy', 'data-pointIdx' => f.options[:child_index], 'data-branchIdx' => f.options[:branchIdx] %>
<%= f.hidden_field :id, 'data-pointIdx' => f.options[:child_index], 'data-branchIdx' => f.options[:branchIdx] %>
<%= f.hidden_field :latitude, 'data-pointIdx' => f.options[:child_index], 'data-branchIdx' => f.options[:branchIdx] %>
<%= f.hidden_field :longitude, 'data-pointIdx' => f.options[:child_index], 'data-branchIdx' => f.options[:branchIdx] %>

app/views/railways/edit.html.erb
<div class="container">
	<h1>Editing railway</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Show', @railway %> |
	<%= link_to 'Back', railways_path %>
</div>

app/views/railways/index.html.erb
<h1>Listing railways</h1>

<table id="railways" class="display" data-source="<%= railways_url(format: "json") %>">
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbreviation</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

<br>

<%= link_to 'New Railway', new_railway_path %>

app/views/railways/new.html.erb
<div class="container">
	<h1>New railway</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Back', railways_path %>
</div>

app/views/railways/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @railway.name %>
</p>

<p>
  <strong>Abbreviation:</strong>
  <%= @railway.abbreviation %>
</p>

<p>
  <strong>Description:</strong>
  <%= @railway.description %>
</p>

<%= link_to 'Edit', edit_railway_path(@railway) %> |
<%= link_to 'Back', railways_path %>

app/views/welcome/index.html.erb
<div class="container">
	<div class="Flexible-container" id="map_canvas"></div>
<div>